### ISSUE TITLE
Missing tag SellerAssignedID and more in profile XRechnung

### ISSUE THREAD

**Issue by mhartmann-weissblau** [stephanstapel/ZUGFeRD-csharp#110]
When using the latest sources from GitHub the tags
- ram:SellerAssignedID
- ram:BuyerAssignedID and
- ram:Description
under parent tag "ram:SpecifiedTradeProduct" are not written to output XML file as before. When I look into the source code I see, that these tags are only written when using profile "Comfort" or "Extended".
I'm not sure, if these fields are fully optional for profile "XRechnung". I could not find any documentation which tells me, if these fields are mandatory or optional.

Michael Hartmann

**Comment by stephanstapel** [comment]
Good point. I guess you are right but I couldn't find any documentation either, maybe this one:

![image](https://user-images.githubusercontent.com/2912080/97866747-cf51f500-1d0c-11eb-825b-3255a703417e.png)

?

**Comment by mhartmann-weissblau** [comment]
Yes, I think the "Item Sellers identifier" from the semantic data model documentation of KosIT should be the missing tag <SellerAssignedID> and this is declared as optional item. I had hoped you have an official documentation because of your change in source code and removing these tags compared to the latest release 4.0.0.

You can buy the syntax mapping of the semantic data model to the real XML tags for CII at German institute for standardization (see https://www.din.de/de/mitwirken/normenausschuesse/nia/veroeffentlichungen/wdc-beuth:din21:270865250).
That's the reason, why there's no official free documentation of the XML tags used for profile "XRechnung".

I think the removal of the tags is OK for profile "XRechnung" (all the mentioned tags are marked as optional in the semantic data model). 

Michael Hartmann

**Comment by stephanstapel** [comment]
I didn't know that, thanks. As an open source initiative, obviously I can't pay anything.
I'll re add the items - they are written to the xml file only if there is any content.

**Comment by Alpini1980** [comment]
Hello,

from "https://www.ferd-net.de/standards/zugferd-2.1.1/zugferd-2.1.1.html" a zip file can be downloaded. It contains a "ZUGFeRD-2.1.1 - Spezifikation_TA.pdf" with the content  "Struktur des CII-Schemas gemäß EN16931-3-3". I guess it contains the same mappings which can be bought from the DIN-Institute in the above mentioned link. It's just ugly to read because to see the full XML path a lot of scrolling up and down is required.

Can anyone confirm that all fields which are mapped from the CII specification into the XRechnung specification are the fields which have a EN16931-ID: BT-xxx or BG-xxx in this document? It would help me a lot to understand the documentation.

![EN16931-3-3](https://user-images.githubusercontent.com/73544666/97879622-7d1acf00-1d20-11eb-839c-5f04dc06c238.png)

Thanks, Stefan

**Comment by stephanstapel** [comment]
good question. Of course this is document is the one I'm using as the primary reference. I'm just missing the XRechnung column :)
