### ISSUE TITLE
PaymentMean TypeCodes

### ISSUE THREAD

**Issue by pkurz** [stephanstapel/ZUGFeRD-csharp#51]
So i got to test again, new version looks promising.
Now i noticed the typecodes for the paymentmeans are wrong (v2.1 haven't tested other versions).
According to the documentation possible values are:
|Code | Type                |
|----|-------------------------|
| 10 | Bargeld                 |
| 20 | Scheck                  |
| 30 | Überweisung             |
| 42 | Payment to bank account |
| 48 | Kartenzahlung           |
| 49 | Lastschrift             |
| 57 | Dauerauftrag            |
| 58 | SEPA Credit Transfer    |
| 59 | SEPA Direct Debit       |
| 97 | Report                  |

**Comment by stephanstapel** [comment]
In fact the list is even longer:

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/documentation/zugferd21de/Dokumentation/DE/EN16931%20code%20lists%20values%20used%20from%202020-02-14.xlsx

**Comment by pkurz** [comment]
In the technical documentation only those are listed, and the validator does not accept for example "1".
Not sure what is the truth here.

**Comment by stephanstapel** [comment]
Thinking about this again and again, I fear that this isn't possible to implement.

Since the amount of possible enum values differs between profiles, we'd need to implement multiple enums. On the other hand, that'd make it impossible to use the library.

I'll make the following:
* renaming the payment mean values to be more meaningful
* add the profiles to the documentation

**Comment by pkurz** [comment]
Yes i think that would be the best way i guess. Or you could work with annotations and check those?
