### ISSUE TITLE
Number of digits in NetPriceProductTradePrice

### ISSUE THREAD

**Issue by alexruett** [stephanstapel/ZUGFeRD-csharp#85]
When the element NetPriceProductTradePrice is written, values (prices) in the sub element ChargeAmount are rounded to two fraction digits.
I've looked in the code and noticed, that this is explicitly done using _writeOptionalAmount in InvoiceDescriptor**21**Writer.Save().

In the  InvoiceDescriptor**20**Writer the value is rounded to 4 digits.

Is there a reason for this or is this just wrong in  InvoiceDescriptor**21**Writer?
Regards.
Thanks.

**Comment by stephanstapel** [comment]
That was required by one of the validators. Honestly, I don't remember if it was the epoconsulting validator or the ferdmc validator. Beyond the schema, there are additional business rules which are checked by the validators. Trying to get things right so that all validators are fine is almost impossible.

**Comment by stephanstapel** [comment]
I think I found the source:
https://www.cen.eu/work/areas/ICT/eBusiness/Documents/CWA%2016356-2.pdf

![image](https://user-images.githubusercontent.com/2912080/93381327-c9897880-f860-11ea-8d5b-597c6098ed3a.png)

**Comment by alexruett** [comment]
Thanks for you quick response.
To cite your comment: "Unit prices are stated with maximum of **4** decimals". So for GrossPriceProductTradePrice and NetPriceProductTradePrice 4 decimals should be correct. (And imho that reflects the reality.)

**Comment by stephanstapel** [comment]
yes, that's what it says for the unit prices. Read: 'max'. The additional business rules still prohibit that.

**Comment by alexruett** [comment]
I'm sorry, but I can't follow. Which additonal business rules prohibit 4 decimals for unit prices?

**Comment by stephanstapel** [comment]
Honestly, I don't remember as I've written before. There were literally hundreds of fixes in the library for making it compliant with the validators.
Please check a version with more decimals with the epoconsulting validator and the ferdmc validator. You might use the test invoice in the test application for this.
If there are no errors, I'll change it back (btw: you can clone the new code since I've fixed #84).

**Comment by alexruett** [comment]
I checked the attached files with these validators:
https://www.zugferd-community.net/en/dashboard/validation
https://portal3.gefeg.com/invoice/validation
Neither found any errors in these files.
The epo validator (https://www.epoconsulting.com/erechnung/xrechnung-validator) only checks X-Rechnung as far as I can see, so these files weren't processed.

[ZUGFeRDTest_Decimals.zip](https://github.com/stephanstapel/ZUGFeRD-csharp/files/5243850/ZUGFeRDTest_Decimals.zip)

**Comment by alexruett** [comment]
My suggestion: the library shouldn't take care of the decimals. This caller should be responsible for the correct number of decimals. Otherwise one can run into rounding problems. If the caller calculates with a different number of decimals, the sums probably wouldn't match.
